services:
  - type: web
    name: mqms-backend
    env: node
    rootDir: server
    buildCommand: npm install && npx prisma generate && npx prisma db push --accept-data-loss && npx prisma db seed
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        value: file:./dev.db
      - key: JWT_SECRET
        sync: false
      - key: PORT
        value: 10000
